name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - gdal
  - affine
  - cartopy
  - matplotlib
  - numexpr
  - owslib
  - pyyaml
  - requests
  - scikit-image
  - scipy
  - shapely
  - unidecode
  - psutil
  - toolz
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - jupyter-resource-usage
  - pip:
    - netCDF4
    - zipstream-new
